version: '2'

volumes:
    logs:
        driver: local

services:
    shoplist:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8081 -t public public/index.php
        environment:
            docker: "true"
        ports:
            - 8081:8081
        volumes:
            - .:/var/www
            - logs:/var/www/logs
